version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: howard900
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
      MYSQL_PASSWORD: howard900
    ports:
      - "3306:3306"
