version: '3.8'

services:
  web:
    build: .
    container_name: php_web
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    environment:
      DB_HOST: mysql-ggxt.render.com
      DB_PORT: 3306
      DB_USER: mydb
      DB_PASSWORD: howard900
      DB_NAME: mydb
