version: '3.8'

services:
  web:
    build: .
    container_name: php_web
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: howard900
      MYSQL_DATABASE: mydb
      MYSQL_USER: mydb
      MYSQL_PASSWORD: howard900
    ports:
      - "3311:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
