version: '3.8'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: howard900
    ports:
      - "3311:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: mysql://root:howard900@mysql:3306/mydb
    ports:
      - "80:80"
    depends_on:
      - mysql
