version: '3.8'

services:
  web:
    build: .
    container_name: php_web
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    environment:
      DB_HOST: sql12.freesqldatabase.com
      DB_USER: sql12726340
      DB_PASSWORD: NYYVTRlGwk
      DB_NAME: sql12726340
