version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: howard900
      MYSQL_DATABASE: mydb
    ports:
      - "3311:3306"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
